# Generated by Django 4.2.13 on 2024-05-31 07:16

from django.db import migrations, models
import django.db.models.deletion
import movieapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('poster', models.ImageField(null=True, upload_to='video/%y', validators=[movieapp.validators.file_size])),
                ('description', models.CharField(max_length=100, null=True)),
                ('rdate', models.CharField(max_length=100, null=True)),
                ('actors', models.CharField(max_length=100, null=True)),
                ('video', models.CharField(max_length=300, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=300)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie_details')),
            ],
        ),
        migrations.AddField(
            model_name='movie_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.user'),
        ),
    ]
